
# SUBSCRIPTION_STATUS = ["START", "ADD", "UNSTART"]
# TOPUP_STATUS = ["NO_TOPUP", "ADD"]

# FREE_PLAN = "FREE_PLAN"
# PERSONAL_MUSIC = "PERSONAL_MUSIC"
# PREMIUM_MUSIC = "PREMIUM_MUSIC"
# PERSONAL_VIDEO = "PERSONAL_VIDEO"
# PREMIUM_VIDEO = "PREMIUM_VIDEO"
# PERSONAL_PODCAST = "PERSONAL_PODCAST"
# PREMIUM_PODCAST = "PREMIUM_PODCAST"

# no. of months
ONE = 1
THREE = 3

# per category price
MUSIC_FREE_PLAN_PRICE = 0
MUSIC_FREE_PLAN_VALIDITY = 1
MUSIC_PERSONAL_PLAN_PRICE = 100
MUSIC_PERSONAL_PLAN_VALIDITY = 1
MUSIC_PREMIUM_PLAN_PRICE = 250
MUSIC_PREMIUM_PLAN_VALIDITY = 3

VIDEO_FREE_PLAN_PRICE = 0
VIDEO_FREE_PLAN_VALIDITY = 1
VIDEO_PERSONAL_PLAN_PRICE = 200
VIDEO_PERSONAL_PLAN_VALIDITY = 1
VIDEO_PREMIUM_PLAN_PRICE = 500
VIDEO_PREMIUM_PLAN_VALIDITY = 3


PODCAST_FREE_PLAN_PRICE = 0
PODCAST_FREE_PLAN_VALIDITY = 1
PODCAST_PERSONAL_PLAN_PRICE = 100
PODCAST_PERSONAL_PLAN_VALIDITY = 1
PODCAST_PREMIUM_PLAN_PRICE = 300
PODCAST_PREMIUM_PLAN_VALIDITY = 3


TOPUP_PLAN_FOUR_DEVICE_PRICE_PER_MONTH = 50
TOPUP_PLAN_TEN_DEVICE_PRICE_PER_MONTH = 100

NO_OF_DAYS_BEFORE_TO_NOTIFY = 10
